ExeBattleship: funcoes.o main.o
	g++ -Wall -std=c++11 funcoes.o main.o -o ExeBattleship -lm
	-rm *.o
funcoes.o:
	g++ -std=c++11 -o funcoes.o -c src/funcoes.cpp
main.o:
	g++ -std=c++11 -o main.o -c src/Executavel.cpp
